### ISSUE TITLE
What is the minimum compatible version?

### ISSUE THREAD

**Issue by xiusin** [webui-dev/zig-webui#10]
```
/Users/xiusin/.cache/zig/p/122076f23d5abf8e9dd2069e6ed5fab237a4000a6409d0e6da902023f6c5d0ab3038/build.zig:65:51: error: no field named 'iterate' in struct 'fs.Dir.OpenDirOptions'
        std.fs.openDirAbsolute(examples_path, .{ .iterate = true }) catch |err| {
                                                  ^~~~~~~
/opt/zig/lib/std/fs.zig:1701:32: note: struct declared here
    pub const OpenDirOptions = struct {
                               ^~~~~~
referenced by:
    build: /Users/xiusin/.cache/zig/p/122076f23d5abf8e9dd2069e6ed5fab237a4000a6409d0e6da902023f6c5d0ab3038/build.zig:45:5
    runBuild__anon_16843: /opt/zig/lib/std/Build.zig:1882:27
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

> 0.12.0-dev.1571+03adafd80

**Comment by jinzhongjia** [comment]
you can use zig `0.11.0` to use.
For zig `nightly`, developed using `0.12.0-dev.1861+412999621`

**Comment by jinzhongjia** [comment]
Since zig rolls back the file traversal scheme of 0.11 on 0.12, this will cause some non-latest nightly builds to fail.

**Comment by jinzhongjia** [comment]
see this issue:https://github.com/ziglang/zig/pull/18076

**Comment by xiusin** [comment]
@jinzhongjia  
Updating nightly again will result in the inability to use most third-party libraries, which is a destructive update. Thank you. 

> eg: error: local variable is never mutated

**Comment by xiusin** [comment]
@jinzhongjia It seems that opening the browser and closing it after compiling does not actually exit the program.

**Comment by jinzhongjia** [comment]
> @jinzhongjia It seems that opening the browser and closing it after compiling does not actually exit the program.

which example?

**Comment by jinzhongjia** [comment]
`public_network_access`, this example will expose a port for browser access. It is normal that the program will not exit automatically after closing the browser window.
Solving this problem is actually simple. You only need to use js to monitor the closing event of the browser and call the closing function of webui.

**Comment by jinzhongjia** [comment]
Other examples will automatically exit the program after the browser is closed.

**Comment by jinzhongjia** [comment]
Aboutexamples, they are zig translations of `webui` c library examples

**Comment by xiusin** [comment]
@jinzhongjia Yes, as you said, it runs successfully.  tks
