### ISSUE TITLE
Unable to build, hash mismatch

### ISSUE THREAD

**Issue by alecstein** [webui-dev/zig-webui#11]
`/zig fetch --save https://github.com/webui-dev/zig-webui/archive/main.tar.gz` produces a `build.zig.zon` with the hash

```zig
    .dependencies = .{
        .@"zig-webui" = .{
            .url = "https://github.com/webui-dev/zig-webui/archive/main.tar.gz",
            .hash = "12203e8f6c6eb2977088f54aa7b182abd0d357efc547612233b02b5a72bd7035096c",
        },
    },
```

but trying to build results in a hash mismatch:

```
Fetch Packages [2/2] zig-webui.webui... /Users/alecstein/.cache/zig/p/12203e8f6c6eb2977088f54aa7b182abd0d357efc547612233b02b5a72bd7035096c/build.zig.zon:8:21: error: hash mismatch: expected: 1220d4b5a9c49e9651c796f1f5a4277e7e4d8e4bdc0122eb98c366466849aa5ca0dd, found: 122076f23d5abf8e9dd2069e6ed5fab237a4000a6409d0e6da902023f6c5d0ab3038
            .hash = "1220d4b5a9c49e9651c796f1f5a4277e7e4d8e4bdc0122eb98c366466849aa5ca0dd",
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If I keep putting in the expected hash, I eventually end up with a 'module not found' error, so that's not a solution.

**Comment by jinzhongjia** [comment]
zig fetch get the latest hash just is `12203e8f6c6eb2977088f54aa7b182abd0d357efc547612233b02b5a72bd7035096c`
The hash `1220d4b5a9c49e9651c796f1f5a4277e7e4d8e4bdc0122eb98c366466849aa5ca0dd` is not correct
I don't know why this happens. This problem cannot be reproduced locally.

Maybe you can deletec `zig-cache` directory and refetch package

**Comment by alecstein** [comment]
Darn, frustrating for us both. Yea I tried deleting the cache before I asked, and I just tried again to be sure, and I get the same error. I wonder what's going on.

**Comment by alecstein** [comment]
I asked on Discord and received this:

> The latest release of Zig has some bugs when computing the hash, and probably the project hasn't been updated to use zig master yet.

**Comment by jinzhongjia** [comment]
aha, master's problem?
wait, let me update to latest nightly version

**Comment by jinzhongjia** [comment]
your zig version is ?
mine is `0.12.0-dev.1872+2b5897836`

**Comment by alecstein** [comment]
Mainly `0.11.0`, but I tried with the latest version earlier as well and repro'd the issue.

**Comment by jinzhongjia** [comment]
I have switch zig `0.11.0`, it also works well, not meet "module not found".

**Comment by alecstein** [comment]
Weird. If I do `zig init-exe` and copy your `build.zig.zon` (or do `zig fetch`), I can repro. Even with a clean cache. There must be something deeper going on. I don't think it's your fault.

**Comment by jinzhongjia** [comment]
my `build.zig.zon`? which ?

**Comment by alecstein** [comment]
The one in the README, first paragraph.

**Comment by jinzhongjia** [comment]
![image](https://github.com/webui-dev/zig-webui/assets/41784264/94c0948d-19a3-424f-96d2-29f25046fc46)

this hash?

**Comment by jinzhongjia** [comment]
That's just an example hash I copied from somewhere else

**Comment by alecstein** [comment]
Not that one. I used the hash that I posted in my original question, the one that came from `zig fetch`.

All I mean to say is: when I start from a clean slate (as far as I can tell, unless there are other cache directories lurking about, which there may be) I can get the error. The cache directory I'm deleting is `~/.cache/zig-cache`.

**Comment by alecstein** [comment]
Hey did you change something?

I used this `1220b627dff5565052341afad637d418cec81f4b23e7700150612f37e1bd30edd04c` and it worked.

**Comment by jinzhongjia** [comment]
I just tried updating the hash of the upstream dependency

**Comment by jinzhongjia** [comment]
Maybe it's just that you didn't pull the latest hash after I updated it?

**Comment by alecstein** [comment]
Wild. That totally worked. Not sure what lesson to take away from that, but still, thank you.

**Comment by alecstein** [comment]
> Maybe it's just that you didn't pull the latest hash after I updated it?

Possibly yea. Anyway, I owe you a coffee. That was really great support, thank you so much!
