### ISSUE TITLE
target has no isNative function

### ISSUE THREAD

**Issue by Rapiddox** [webui-dev/zig-webui#14]
error: no field or member function named 'isNative' in 'Build.ResolvedTarget'

it's now `target.query.isNative()` if I see that right in the latest 0.12 dev build

**Comment by jinzhongjia** [comment]
This problem is known and the api adaptation has been completed, but there is a bug in the nightly version of the official website that prevents it from being built correctly.

**Comment by jinzhongjia** [comment]
now branch `zig_build_api_change` is available, but you need to build zig manually.

more details, see this issue: https://github.com/ziglang/zig/pull/18445

**Comment by jinzhongjia** [comment]
Now everything should be able to build, except for the dynamic linker on the windows platform, which is a bug in zig itself.
