### ISSUE TITLE
Integrating Webui Directly in Project

### ISSUE THREAD

**Issue by wwderw** [webui-dev/zig-webui#27]
Instead of having webui as a module is it possible to integrate everything directly into the project?

Just using the minimal example my build.zig is:

```
const std = @import("std");
const Cflags = &.{};


pub fn build(b: *std.Build) void {

    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "programName",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });
    //Adding Webui to the project
    exe.addCSourceFile(.{
        .file =.{
            .path = "./webui/src/webui.c"},

        .flags = Cflags,
    });
    exe.addIncludePath(.{
        .path="./webui/include/",
    });

     exe.linkLibC();

    b.installArtifact(exe);



    const run_cmd = b.addRunArtifact(exe);


    run_cmd.step.dependOn(b.getInstallStep());


    if (b.args) |args| {
        run_cmd.addArgs(args);
    }


    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

And my main.zig is:

```
const std = @import("std");
const web = @cImport({
    @cInclude("webui.hpp");
});

pub fn main() !void {
    const nwin = web.webui_new_window();
    _ = web.webui_show(nwin, "<html><script src=\"webui.js\"></script> Hello World from C! </html>");

    web.webui_wait();
}
```

The paths for atleast the include appear to be correct as I do get code completion from zls.  It just doesn't appear to be build, so I'm pretty sure I'm missing something from the build.zig or maybe can't do what I'm attempting to do.

Appreciate any help.  Thanks.

**Comment by wwderw** [comment]
Silly.  I forgot the cflags.

I have updated in my build.zig: 
```
const CFlags = &.{"-pthread", "-m"};
```

Now, I actually get an error message that says "-m" is unknown.

**Comment by jinzhongjia** [comment]
Sorry, I am currently on vacation and do not have a computer with me, so I can only provide limited replies.

**Comment by jinzhongjia** [comment]
In fact, your idea is completely feasible, and even the current release version can directly use webui as a C library (ignore webui's build.zig)
Directly reference the C library files and compile them. I still use webui as a module to ensure 0.11 compatibility.

**Comment by jinzhongjia** [comment]
Need to know what zig version you are currently using
You can refer to this code. I extracted the code for compiling the C library separately as a function. https://github.com/webui-dev/webui/blob/24fefb865b2d8de188b3344981635c9f99a26dec/build_12.zig#L38-L86

**Comment by jinzhongjia** [comment]
Of course, I will probably start working normally the day after tomorrow, and I will be able to give a more detailed answer then.

**Comment by wwderw** [comment]
Thanks!  I'll see what I get for the function that you referenced.  Just started to really try my hand at zig, so I'm sure it's more of I just know enough to cause damage type of thing.

I am using the latest release of Zig. 0.12

Thanks!

**Comment by jinzhongjia** [comment]
I have made `zig-webui` independent for `webui`, it will build webui from scratch

See this: https://github.com/webui-dev/zig-webui/blob/5e23270ae8ff6f5580319eb3c12aacbbf8aa6437/build_12.zig#L63-L114

**Comment by wwderw** [comment]
OS is Arch (I can build webui using make just fine), compiler would be whatever zig uses as default, LLVM I think.  I wouldn't be surprised if my build script is all janky though.  Like I said, I know enough to cause damage.

I couldn't find a whole lot in the way of directly using C libs within zig most of the time it's via modules unless it was just a simple header file, so this may be above my means at this stage.

**Comment by jinzhongjia** [comment]
> OS is Arch (I can build webui using make just fine), compiler would be whatever zig uses as default, LLVM I think. I wouldn't be surprised if my build script is all janky though. Like I said, I know enough to cause damage.
> 
> I couldn't find a whole lot in the way of directly using C libs within zig most of the time it's via modules unless it was just a simple header file, so this may be above my means at this stage.

In zig, we can simply treat the c file as a zig file, use `addCSourceFile` to add the c source file, and `addIncludePath` to add the header file search path. All dependencies of the corresponding module will be automatically recognized by the current project.

What we actually need is to add c files, header files, and pass the corresponding cflags. We may also need to link to some libraries(with `linkSystemLibrary`)

**Comment by wwderw** [comment]
I took the "-m" out of the CFlags variable and I added `exe.linkSystemLibrary("webui");` and that seems to have done a build.  Strange that it needs "-m" using gcc, but not on this one.

**Comment by wwderw** [comment]
I took the "-m" out of the CFlags variable and I added `exe.linkSystemLibrary("webui");` and that seems to have done a build.  Strange that it needs "-m" using gcc, but not with zig.

**Comment by jinzhongjia** [comment]
Have you used `linkSystemLibrary` to link to aur's `webui`?

With using zig, there is no need to link system `webui` libraries, because the lib can be statically built and linked!

**Comment by wwderw** [comment]
No.  Even though I'm on Arch and most people use Arch for the AUR, I actually don't touch it, nor really the main repo. 

Previously I always built webui (or most any lib I used) from source, especially since I liked to link to musl.  I do not have any system wide install of webui at this time as well (wanted to make sure that I wasn't getting a false sense of something working when it wasn't quite right).
