### ISSUE TITLE
Unable to find artifact "webui" on zig-0.12

### ISSUE THREAD

**Issue by edmBernard** [webui-dev/zig-webui#32]
Hello, 

I tried zig-webui with zig version 0.12 the last stable release. 

I got the error : 
```
thread 168387 panic: unable to find artifact 'webui'
```

it seems to be really close the one of the previous issue where the fix was done for previous zig version. 
https://github.com/webui-dev/zig-webui/issues/16

**Comment by jinzhongjia** [comment]
I will fix this problem tomorrow

**Comment by jinzhongjia** [comment]
Maybe you need to show your `build.zig`, regarding the issue https://github.com/webui-dev/zig-webui/issues/16 you mentioned, there was a problem only in 0.11 (caused by my mistake), that should be no problem
