### ISSUE TITLE
losing events

### ISSUE THREAD

**Issue by sensiblearts** [webui-dev/zig-webui#57]
For the last week or so, I'm losing all events except Connect and Disconnect. 

I'm not getting mouse clicks or navigation.

Did the API change?

**Comment by jinzhongjia** [comment]
In the past, we just added new APIs and separated the code into multiple files. This time, the logic is clearer.

Theoretically speaking, it will not have any impact on the library. After all, the examples are all passed.
can you give me a minimal instance

**Comment by sensiblearts** [comment]
That "custom SPA example" example in the other PR that I just submitted -- that one only shows CONNECT and DISCONNECT.

Also, your custom_web_server example: when I click back and forth from index.html to second.html, I get this:
```
Disconnected.
Connected.
Disconnected.
Connected.
Disconnected.
Connected.
Disconnected.
Connected.
```

It seems like these apps were showing any mouse click, and navigation events, as recently as last week.

**Comment by sensiblearts** [comment]
Good night. More tomorrow if you need it.

**Comment by jinzhongjia** [comment]
The example is normal, it is just synchronized with the upstream example.
![icture](https://github.com/webui-dev/zig-webui/assets/41784264/6f3e7f20-5cff-4935-b794-c985df678239)

**Comment by sensiblearts** [comment]
Thank you, the click events are back.

However, now, navigation events cause disconnection and `wait` ends. This happens for the `custom_web_server` example:
```
my_backend_func 1: 123
my_backend_func 2: 456
my_backend_func 3: 789
Click.
Click.
Click.
Click.
Click.
Click.
Starting navigation to: http://localhost:8080/second.html
Disconnected.
```
 And it happens for my own example (custom_spa_server_on_free_port) that does client-side navigation. So it's just _receiving_ the event that breaks it.

I will try to debug it after work today.

**Comment by sensiblearts** [comment]
Thank you!
