### ISSUE TITLE
Build zig-webui on Windows 11, Linking errors

### ISSUE THREAD

**Issue by z1fire** [webui-dev/zig-webui#6]
OS: Windows 11
Zig Version: 0.12.0-dev.1856+94c63f31f

zig build run_minimal
info(WebUI): link mode is static
zig build-exe minimal Debug native: error: the following command failed with 24 compilation errors:

![image](https://github.com/webui-dev/zig-webui/assets/80300887/32743f30-c4f1-4225-aacc-7efae41659ab)
![image](https://github.com/webui-dev/zig-webui/assets/80300887/46b27a02-6c36-4f1b-8224-ab8208c681ed)
![image](https://github.com/webui-dev/zig-webui/assets/80300887/0d1826fa-be38-4962-bd3f-98c45420f223)
![image](https://github.com/webui-dev/zig-webui/assets/80300887/d3205a6d-912f-4554-abb1-a1a941124555)

**Comment by jinzhongjia** [comment]
Please not use `zig build-exe`...

Instead of that, using `zig build run_minimal` to build minimal examples

**Comment by jinzhongjia** [comment]
the command `zig build --help` should tell you how to do
![image](https://github.com/webui-dev/zig-webui/assets/41784264/02325cd7-c0b3-467c-aa09-239ebf4c1eb4)

**Comment by jinzhongjia** [comment]
Like `zig build run_minimal`, this will build and run `minimal` examples
Same for other things.

Please not use `zig build-exe`, this command is designed to build a single file zig, sometimes it is also used as a debugger

**Comment by jinzhongjia** [comment]
Add this `exe.linkSystemLibrary("ws2_32");`  to line 118 in `build.zig`, then try recompile it

**Comment by jinzhongjia** [comment]
The latest commit should have fixed the issue

**Comment by z1fire** [comment]
![image](https://github.com/webui-dev/zig-webui/assets/80300887/fa8ffb45-be69-4311-ad28-af0e3dcf10b4)
It does

**Comment by z1fire** [comment]
I can confirm that zig-webui works using OS: Windows 11
Zig Version: 0.12.0-dev.1856+94c63f31f

Yay for my first Github issue post!
