### ISSUE TITLE
Minimizing and hiding console/cmd windows

### ISSUE THREAD

**Issue by sensiblearts** [webui-dev/zig-webui#62]
Hi @jinzhongjia , this is a minor issue for `zig-webui` per se, but it's close enough that I thought I'd post it here given your interest in Zig. 

There was an earlier WebUI issue asking about [how to hide the console](https://github.com/webui-dev/webui/issues/328) and you told the questioner about setting `exe.subsystem = .Windows;` in `build.zig`.  This was very helpful information and I'm wondering how it can be highlighted better. Somewhere in the [Documentation](https://webui.me/docs)? Or as an Example with its own build.zig?

Also related: I am developing an app that spawns a `std.process.Child`, (a NodeJS process) and I would like to minimize its console window to the task bar. As far as I can tell, either the Zig `Child` code would have to be modified, or I will have to write my own `C` code to call (on Windows) `CreateProcess`. I am new to Zig and Ziggit, so I thought I'd ask you: Do you think it is appropriate to request a modification to `std.process.Child.spawn` so that startup parameters can be passed as arguments? (Such as, on Windows, STARTUPINFO)?  I [asked about it at  Ziggit](https://ziggit.dev/t/child-spawn-with-sw-minimize-possible/5210), so maybe I will have some feedback soon. Let me know if you're interested in the result. 

(p.s., I will close this soon after I post it; it's mostly FYI.)

**Comment by jinzhongjia** [comment]
In fact, regarding the subsystem settings, I have also considered where to explain this issue.
But it seems inappropriate to put it anywhere. Maybe it should be placed where the readme package is installed.

**Comment by jinzhongjia** [comment]
The second question, I don’t know it
