### ISSUE TITLE
@embedFile Usage with set_file_handler?

### ISSUE THREAD

**Issue by wwderw** [webui-dev/zig-webui#63]
What is the best way to use set_file_handler to return the embedFile?

I'm not directly using the bindings.  I'm doing @cImport and using it that way, but I seem to have a problem with getting it to return the embedFile data.  For instance, when using C, I'll have my assets linked using the linker, so I'll define _binary_logo_png_start (or whatever the asset is) and have that return in the file handler callback.  Essentially the same thing with Nim as well, but like Zig, it is easier to embed the files.  

Is there a way to do that using Zig using the set_file_handler?

**Comment by jinzhongjia** [comment]
Of course, I have updated the example with `@embedFile`, you can see this, https://github.com/webui-dev/zig-webui/tree/main/examples/serve_a_folder

This should meet your needs

If you have additional questions I suggest showing a sample code. Or a more detailed description of requirements

**Comment by wwderw** [comment]
Ok, I was looking off the zig version of the docs, so I didn't see that you had an example with @embed.  I was doing something similar, but I don't know if it's because I was directly importing it and using it versus using the bindings.

Attached is an example.  If I take out the file_handler, everything else works like it should.  So I don't know if I'm handling the file_handler incorrectly or if there is something else that I need to do before I return the contents.

[test.txt](https://github.com/user-attachments/files/16342790/test.txt)

**Comment by jinzhongjia** [comment]
https://github.com/webui-dev/zig-webui/blob/96af9ece9dba546f6b38348252426c82b541ed96/examples/serve_a_folder/main.zig#L4-L5

**Comment by wwderw** [comment]
Yea, I had seen those two from the link.  And how you handled it with atleast the test_txt is how I handled it (see test.txt attachment as that is my main.zig file, I had to change the extention to upload it here).  I think I had led to some confusion with my naming schema and your example.

**Comment by jinzhongjia** [comment]
```zig
fn file_handler(filename: []u8) ?[]u8 {
    if (mem.eql(u8, filename, "/logo.png")) {
        return logo;
    }
    return null;
}
```
this function is error....
wait a minute, I'll show you how to use it correctly

**Comment by jinzhongjia** [comment]
code gist: https://gist.github.com/jinzhongjia/e9335d881e073a9e04586670fd2bc25d

and the png is here: https://github.com/zigcc/zig-course/blob/main/course/public/android-chrome-512x512.png

**Comment by jinzhongjia** [comment]
Implementation details of `zig-webui`:

https://github.com/webui-dev/zig-webui/blob/96af9ece9dba546f6b38348252426c82b541ed96/src/webui.zig#L171-L185

I made a compile-time wrapper, which allows us to more flexibly use the features of zig instead of the c way of writing

**Comment by jinzhongjia** [comment]
![image](https://github.com/user-attachments/assets/1af705cd-17c1-4e3e-a506-70f52afa19ea)
This is a picture of the running effect of gist

**Comment by wwderw** [comment]
Aahhhh, I see what happened.  I was able to get it to work, thank you for the help.  I'm slowly trying to get into it.  I don't know if I'm ready to go full until the zig way of doing things.  Skill issues and all that.

Thanks again for the help.
