### ISSUE TITLE
macOS: Keyboard events aren't forwarded to the WebView

### ISSUE THREAD

**Issue by thundron** [webui-dev/zig-webui#64]
On macOS, when loading a website, the input is not forwarded to the window but remains in the terminal.
Code to reproduce:
```zig
const std = @import("std");
const webui = @import("webui");

pub fn main() !void {
    // Create new windows
    var nwin = webui.newWindow();

    // Show a new WebView window
    _ = nwin.showWv("https://www.google.com");

    // Wait until all windows get closed
    webui.wait();

    // Free all memory resources (Optional)
    webui.clean();
}
```
Moreover, the instance eventually quits by itself after some ~10 seconds

**Comment by jinzhongjia** [comment]
So can we close this issue?

**Comment by thundron** [comment]
I think it should be possible to open the webview and interact with the keyboard even without connection to the backend.
I don't need it for what I'm trying to do so it shouldn't be a requirement in my opinion; I just need to open the webview and interact with it normally

**Comment by jinzhongjia** [comment]
In order for webui to correctly control the webview, it needs to inject webui.js, otherwise the webview will be out of control. This is why webui will forcefully kill the webview when it cannot connect to the webview.

**Comment by thundron** [comment]
But I don't need webui to control the webview, just spawn it and eventually kill it (if needed) which as far as I understand, it can already do even without injecting webui.
If it's against your intended design, that's another story

**Comment by jinzhongjia** [comment]
This cannot be solved by the wrapper. Maybe you can make a request to the webui main repository.

**Comment by thundron** [comment]
Gotcha, thanks!
