### ISSUE TITLE
Support `webui` debug version 

### ISSUE THREAD

**Issue by mochalins** [webui-dev/zig-webui#72]
The Zig `webui` wrapper should allow for building and using the debug `webui` library as a dependency, preferably with an easy to use build option.

**Comment by jinzhongjia** [comment]
Sorry, I have other things to do recently. I will fix this issue end of next month

**Comment by mochalins** [comment]
No problem, I actually plan on working on this soon!

**Comment by mochalins** [comment]
Apologies, I'm not sure why GitHub auto-closed this issue.

**Comment by mochalins** [comment]
Well, anyhow this can now be closed with #70 being merged. As of now, building the Zig webui bindings in Debug mode will automatically enable webui C library logs.
