### ISSUE TITLE
Why can't I get dependencies?

### ISSUE THREAD

**Issue by Super1Windcloud** [webui-dev/zig-webui#73]
![image](https://github.com/user-attachments/assets/1aee9e14-d3d2-4447-9401-6a5e3e5b3839)

**Comment by Super1Windcloud** [comment]
0.13

**Comment by jinzhongjia** [comment]
检查你的代理，换个好点的梯子（该问题一般出现于代理服务器返回内容丢失）
Check your proxy

**Comment by jinzhongjia** [comment]
> @jinzhongjia Any idea?

There is no other problem, it's just that there's something wrong with the proxy server he's using.

**Comment by Super1Windcloud** [comment]
yes  ,thank you ,   I  already  know reason
